### ISSUE TITLE
A more innovative project sort option for 'idea hotness'

### ISSUE THREAD

**Issue by pete2786** [coeventer/ccf#94]
Something using recency of submission, vote, comment or volunteer which can kind of create a 'hotness' sort option. Looking for ideas/suggestions on how to weight or implement a formula or calculation.

**Comment by pete2786** [comment]
https://github.com/campuscodefest/ccf/blob/project_hotness/app/services/project_hotness.rb

@chadfennell thoughts?

**Comment by chadfennell** [comment]
Cool idea. Not an area I'm at all well versed in, but some initial thoughts...

In the context of a single event, a hotness sort would only be relevant while the event is open for new submissions since a decay rate implies new/recent content. On the other hand, it would be cool (at some point down the road) to feature hot projects across multiple events. But yes, I can see having a hotness sort during or running up to an event. I can also see having to tweak the decay rate based on how active users are with new submissions. 

Another, simpler sort, might be "total activity", which would give you hotness without the decay rate. Unfortunately, this results in a rich get richer situation. This might be useful though once an event is done and cannot receive new votes, submissions, comments, etc.

**Comment by chadfennell** [comment]
Stupid question. I'm assuming this: https://github.com/campuscodefest/ccf/blob/project_hotness/app/services/project_hotness.rb#L20

is to prevent having a  1 / Math.log(1) situation (or Math.log(-n)).

Any reason why it couldn't be expressed as 

`return 1 if created_days_ago <= decay_rate + 1`

probably I'm missing something though. Thanks for doing this, interesting idea.

**Comment by pete2786** [comment]
Regarding comment above, yes it was just some general hacking to avoid infinity, o for Log(0) and log(1),  and Log(2) was less than 1, so dividing it has a total greater than one. Probably better solutions out there, just what I had thus far.

**Comment by pete2786** [comment]
I do like the idea of the decay rate being relative to the event activity as well, I hadn't thought that far ahead.

**Comment by chadfennell** [comment]
Sweet, well, I say go for it.

**Comment by pete2786** [comment]
The hotness is now the default search!
